Task3
sergey-berezin/441_elfimova pull request #3
Opened 2022-11-27 22:52 UTC by QuantumDealer

In progress

2022-12-02 08:22 UTC, sergey-berezin requested changes
1) Проект grid не компилируется.
2) Опять "просочилась" папка .vs

2022-12-02 08:22 UTC, sergey-berezin commented on grid/Grid/Grid.csproj
> +      <HintPath>..\..\..\..\GitHub\441_elfimova\lib\obj\Debug\net6.0\EmotionFerPlus.dll</HintPath>
К проекту `grid` должен быть подключён пакет NuGet из первого задания или проект из первого задания. Добавлять ссылку на результат сборки - неправильно.

2022-12-02 08:22 UTC, sergey-berezin commented on grid/Grid/Grid.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.0">
Нужно подключить пакет `Miсrosoft.EntityFrameworkCore.Sqlite`, иначе проект не собирается.

2022-12-02 08:22 UTC, sergey-berezin commented on grid/Grid/Migrations/init.cs
> +using Microsoft.EntityFrameworkCore;
С какой целью этот файл помещён именно в папку `Migrations`. В эту папку обычно помещается машинно-сгенерированный код.

2022-12-02 08:22 UTC, sergey-berezin commented on grid/Grid/MainWindow.xaml.cs
> +                    neutral.ItemsSource = neutralCollection;
Присваивать `ObservableCollection` на каждой итерации цикла не нужно.

2022-12-09 08:28 UTC, sergey-berezin requested changes
1) При добавлении изображения возникает исключение
2) В проект `grid` опять _просочилась_ папка `.vs`

2022-12-09 08:28 UTC, sergey-berezin commented on grid/Grid/MainWindow.xaml.cs
> +                            db.Add(new EmotionsTable
На этой строке возникает исключение:

![image](https://user-images.githubusercontent.com/3417017/206657065-050fe0ca-23b7-4cb5-9e9e-007a88ac116a.png)

2022-12-09 08:28 UTC, sergey-berezin commented on grid/Grid/init.cs
> +    public string fileName { get; set; }
Не самое лучшее решение, т.к. имена файлов могут совпадать для разных изображений. Например, вы загрузили в БД файл `C:\tmp\1.jpg`, затем стёрли его, затем сохранили под этим именем другое изображение. 

Лучше использовать в качестве ключа автоматически создаваемый `int`, а имя файла использовать просто в качестве свойства.

2022-12-09 08:28 UTC, sergey-berezin commented on grid/Grid/init.cs
> +    public string fileName { get; set; }
Это свойство явно используется для связи таблицей `ImagesTable`, но EF Core и БД про это не знают. Надо использовать атрибут `[ForeignKey]` или навигационное свойство.

2022-12-15 21:44 UTC, QuantumDealer commented
Проверила у себя, все работает. Работаю над 4 заданием.

2022-12-19 07:58 UTC, sergey-berezin commented
Удалите папку .vs и я приму этот PR.

2022-12-20 14:10 UTC, merged